/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogbookRouteImport } from './routes/logbook'
import { Route as LearningPathRouteImport } from './routes/learning-path'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogbookIndexRouteImport } from './routes/logbook.index'
import { Route as LearningPathIndexRouteImport } from './routes/learning-path.index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LogbookIdRouteImport } from './routes/logbook.$id'
import { Route as LearningPathModuleIdRouteImport } from './routes/learning-path.$moduleId'
import { Route as EquipmentIdRouteImport } from './routes/equipment.$id'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminEquipmentRouteImport } from './routes/admin.equipment'
import { Route as AdminDownloadsRouteImport } from './routes/admin.downloads'
import { Route as ApiFilesFilenameRouteImport } from './routes/api.files.$filename'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogbookRoute = LogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathRoute = LearningPathRouteImport.update({
  id: '/learning-path',
  path: '/learning-path',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogbookIndexRoute = LogbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogbookRoute,
} as any)
const LearningPathIndexRoute = LearningPathIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearningPathRoute,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipmentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LogbookIdRoute = LogbookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LogbookRoute,
} as any)
const LearningPathModuleIdRoute = LearningPathModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => LearningPathRoute,
} as any)
const EquipmentIdRoute = EquipmentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EquipmentRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipmentRoute = AdminEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AdminRoute,
} as any)
const ApiFilesFilenameRoute = ApiFilesFilenameRouteImport.update({
  id: '/api/files/$filename',
  path: '/api/files/$filename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/learning-path': typeof LearningPathRouteWithChildren
  '/logbook': typeof LogbookRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/learning-path/$moduleId': typeof LearningPathModuleIdRoute
  '/logbook/$id': typeof LogbookIdRoute
  '/admin/': typeof AdminIndexRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/learning-path/': typeof LearningPathIndexRoute
  '/logbook/': typeof LogbookIndexRoute
  '/api/files/$filename': typeof ApiFilesFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/learning-path/$moduleId': typeof LearningPathModuleIdRoute
  '/logbook/$id': typeof LogbookIdRoute
  '/admin': typeof AdminIndexRoute
  '/equipment': typeof EquipmentIndexRoute
  '/learning-path': typeof LearningPathIndexRoute
  '/logbook': typeof LogbookIndexRoute
  '/api/files/$filename': typeof ApiFilesFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/learning-path': typeof LearningPathRouteWithChildren
  '/logbook': typeof LogbookRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/learning-path/$moduleId': typeof LearningPathModuleIdRoute
  '/logbook/$id': typeof LogbookIdRoute
  '/admin/': typeof AdminIndexRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/learning-path/': typeof LearningPathIndexRoute
  '/logbook/': typeof LogbookIndexRoute
  '/api/files/$filename': typeof ApiFilesFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/auth'
    | '/downloads'
    | '/equipment'
    | '/learning-path'
    | '/logbook'
    | '/profile'
    | '/quiz'
    | '/admin/downloads'
    | '/admin/equipment'
    | '/admin/logs'
    | '/admin/modules'
    | '/equipment/$id'
    | '/learning-path/$moduleId'
    | '/logbook/$id'
    | '/admin/'
    | '/equipment/'
    | '/learning-path/'
    | '/logbook/'
    | '/api/files/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/auth'
    | '/downloads'
    | '/profile'
    | '/quiz'
    | '/admin/downloads'
    | '/admin/equipment'
    | '/admin/logs'
    | '/admin/modules'
    | '/equipment/$id'
    | '/learning-path/$moduleId'
    | '/logbook/$id'
    | '/admin'
    | '/equipment'
    | '/learning-path'
    | '/logbook'
    | '/api/files/$filename'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/auth'
    | '/downloads'
    | '/equipment'
    | '/learning-path'
    | '/logbook'
    | '/profile'
    | '/quiz'
    | '/admin/downloads'
    | '/admin/equipment'
    | '/admin/logs'
    | '/admin/modules'
    | '/equipment/$id'
    | '/learning-path/$moduleId'
    | '/logbook/$id'
    | '/admin/'
    | '/equipment/'
    | '/learning-path/'
    | '/logbook/'
    | '/api/files/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiAssistantRoute: typeof AiAssistantRoute
  AuthRoute: typeof AuthRoute
  DownloadsRoute: typeof DownloadsRoute
  EquipmentRoute: typeof EquipmentRouteWithChildren
  LearningPathRoute: typeof LearningPathRouteWithChildren
  LogbookRoute: typeof LogbookRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  ApiFilesFilenameRoute: typeof ApiFilesFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logbook': {
      id: '/logbook'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof LogbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-path': {
      id: '/learning-path'
      path: '/learning-path'
      fullPath: '/learning-path'
      preLoaderRoute: typeof LearningPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logbook/': {
      id: '/logbook/'
      path: '/'
      fullPath: '/logbook/'
      preLoaderRoute: typeof LogbookIndexRouteImport
      parentRoute: typeof LogbookRoute
    }
    '/learning-path/': {
      id: '/learning-path/'
      path: '/'
      fullPath: '/learning-path/'
      preLoaderRoute: typeof LearningPathIndexRouteImport
      parentRoute: typeof LearningPathRoute
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof EquipmentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/logbook/$id': {
      id: '/logbook/$id'
      path: '/$id'
      fullPath: '/logbook/$id'
      preLoaderRoute: typeof LogbookIdRouteImport
      parentRoute: typeof LogbookRoute
    }
    '/learning-path/$moduleId': {
      id: '/learning-path/$moduleId'
      path: '/$moduleId'
      fullPath: '/learning-path/$moduleId'
      preLoaderRoute: typeof LearningPathModuleIdRouteImport
      parentRoute: typeof LearningPathRoute
    }
    '/equipment/$id': {
      id: '/equipment/$id'
      path: '/$id'
      fullPath: '/equipment/$id'
      preLoaderRoute: typeof EquipmentIdRouteImport
      parentRoute: typeof EquipmentRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipment': {
      id: '/admin/equipment'
      path: '/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AdminEquipmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/files/$filename': {
      id: '/api/files/$filename'
      path: '/api/files/$filename'
      fullPath: '/api/files/$filename'
      preLoaderRoute: typeof ApiFilesFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminEquipmentRoute: typeof AdminEquipmentRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminEquipmentRoute: AdminEquipmentRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EquipmentRouteChildren {
  EquipmentIdRoute: typeof EquipmentIdRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
}

const EquipmentRouteChildren: EquipmentRouteChildren = {
  EquipmentIdRoute: EquipmentIdRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
}

const EquipmentRouteWithChildren = EquipmentRoute._addFileChildren(
  EquipmentRouteChildren,
)

interface LearningPathRouteChildren {
  LearningPathModuleIdRoute: typeof LearningPathModuleIdRoute
  LearningPathIndexRoute: typeof LearningPathIndexRoute
}

const LearningPathRouteChildren: LearningPathRouteChildren = {
  LearningPathModuleIdRoute: LearningPathModuleIdRoute,
  LearningPathIndexRoute: LearningPathIndexRoute,
}

const LearningPathRouteWithChildren = LearningPathRoute._addFileChildren(
  LearningPathRouteChildren,
)

interface LogbookRouteChildren {
  LogbookIdRoute: typeof LogbookIdRoute
  LogbookIndexRoute: typeof LogbookIndexRoute
}

const LogbookRouteChildren: LogbookRouteChildren = {
  LogbookIdRoute: LogbookIdRoute,
  LogbookIndexRoute: LogbookIndexRoute,
}

const LogbookRouteWithChildren =
  LogbookRoute._addFileChildren(LogbookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiAssistantRoute: AiAssistantRoute,
  AuthRoute: AuthRoute,
  DownloadsRoute: DownloadsRoute,
  EquipmentRoute: EquipmentRouteWithChildren,
  LearningPathRoute: LearningPathRouteWithChildren,
  LogbookRoute: LogbookRouteWithChildren,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  ApiFilesFilenameRoute: ApiFilesFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
